name: Go Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check if build output exists
        run: test -d cmd
        id: build_output_exists

      - name: Build
        if: ${{ !steps.build_output_exists.outputs.result }}
        run: go build -v ./...

      - name: Run Tests
        run: go test -v ./...
