name: Go Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
          
      - name: Compile
        run: mkdir -p build && go build -o build/test ./... 

      - name: Clean Build Output
        run: rm -rf build

      - name: Run Tests
        run: go test -v ./...
